### ISSUE TITLE
"Finish map" dialog is invisble in fullscreen when embedded

### ISSUE THREAD

**Issue by fnoks** [otacke/h5p-game-map#51]
How to reproduce:
- Embed a Game Map through the iframe embed code
- Open it in fullscreen
- Finish it

You'll notice the "Finish Map" dialog is not visible, but it will become visible when leaving fullscreen.

**Comment by otacke** [comment]
Thanks! I'll check that later today.

**Comment by otacke** [comment]
@fnoks There's a bug. I can reproduce the behavior.

I think the bug is in H5P core though. It happens with any H5P content that uses the H5P.ConfirmationDialog class when in fullscreen mode. Cmp. e.g.
- Course Presentation: https://otacke.h5p.com/content/1292120357340996547/embed
- Interactive Book: https://otacke.h5p.com/content/1292120361517939377/embed

Consistent in Chrome, Firefox and Safari. Have not located the source yet, however.

**Comment by otacke** [comment]
Seems like there's a problem in GameMap and some other H5P component as well, potentially H5P Question that's used by H5P.MultiChoice for the confirmation dialog.

Fixed by https://github.com/otacke/h5p-game-map/pull/53
