### ISSUE TITLE
Change size of dots

### ISSUE THREAD

**Issue by VyFabo** [otacke/h5p-game-map#83]
Would it be possible to allow authors to adapt the size of the dots for each stage?

**Comment by otacke** [comment]
This could be possible, but I won't add it. The stages may seem too large for your taste, but on smaller screens they barely meet the accessibility size requirements for actionable elements. Since people would be likely to shrink down the stages and create content that's difficult to use for people with movement disorders, I decided to be patronizing here and to not allow this.
